{
  "attributes": {
    "tester": "tester",
    "start_time": "2020-07-03 01:38:36",
    "duration": "0:00:00.000622"
  },
  "report": {
    "test_list": [
      {
        "desc": "testDemo.TestDemo: testDemo_doc",
        "count": 1,
        "Pass": 0,
        "fail": 1,
        "error": 0,
        "id": 1,
        "test_list": [
          {
            "tid": "ft1_1",
            "Class": "none",
            "style": "failCase",
            "desc": "test_foo_1: test_demo1_doc",
            "status": 1,
            "ue": "Traceback (most recent call last):\n  File \"/Users/lanyuting/repositories/read_unittest/cases/testDemo.py\", line 11, in test_foo_1\n    self.assertTrue(False)\nAssertionError: False is not true\n",
            "uo": "test_demo1 running\n"
          }
        ]
      },
      {
        "desc": "test_foo.TestFoo: testFoo_doc",
        "count": 2,
        "Pass": 0,
        "fail": 2,
        "error": 0,
        "id": 2,
        "test_list": [
          {
            "tid": "ft2_1",
            "Class": "none",
            "style": "failCase",
            "desc": "test_foo_1: test_foo1_doc",
            "status": 1,
            "ue": "Traceback (most recent call last):\n  File \"/Users/lanyuting/repositories/read_unittest/cases/test_foo.py\", line 11, in test_foo_1\n    self.assertTrue(False)\nAssertionError: False is not true\n",
            "uo": "test_foo1 running\n"
          },
          {
            "tid": "ft2_2",
            "Class": "none",
            "style": "failCase",
            "desc": "test_foo_2: test_foo2_doc",
            "status": 1,
            "ue": "Traceback (most recent call last):\n  File \"/Users/lanyuting/repositories/read_unittest/cases/test_foo.py\", line 17, in test_foo_2\n    self.assertTrue(False)\nAssertionError: False is not true\n",
            "uo": "test_foo2 running\n"
          }
        ]
      }
    ],
    "count": "3",
    "Pass": "0",
    "fail": "3",
    "error": "0",
    "pass_rate": null
  }
}